### PR TITLE
Update Spanish translation.

### PR DESCRIPTION
**Pull request by darkshram**

### CODE REVIEW

**Comment by mhogomchungu** [comment]
Sorry, three more strings where just added.

**Comment by darkshram** [comment]
> Sorry, three more strings where just added.

Ok. Give me a few minutes and will make a new PR.

**Comment by mhogomchungu** [comment]
I plan to make a new release on june 1st, 2021 and there are a few new strings to be translated.

Thanks in advance.

**Comment by darkshram** [comment]
Ok. Will do it today.

**Comment by darkshram** [comment]
Done.

**Pull request merged**
