### PR TITLE
New language: Brazilian Portuguese

### PR DESCRIPTION
**Pull request by Marcelozoo**
I translated it into Brazilian Portuguese.

Note: I changed the translator.cpp file and added the Brazilian language on line 39. I just copied and pasted line 38 and changed the parameters. I believe it is correct.

### CODE REVIEW

**Comment by mhogomchungu** [comment]
There are a few more strings to translate.

**Comment by Marcelozoo** [comment]
> There are a few more strings to translate.

The pt_BR files.ts and pt_BR.qm have been updated with the translation of the new words.

**Comment by mhogomchungu** [comment]
You have to make a new pull request.

**Comment by mhogomchungu** [comment]
New version with your translations will be released on March 1st, 2023.

**Comment by mhogomchungu** [comment]
New version is out and it has your translations, thank you

https://github.com/mhogomchungu/media-downloader/releases/tag/2.9.0

**Pull request merged**
